### ISSUE TITLE
MMU2S isses with Firmware 3.14.0 (3.0.2)

### ISSUE THREAD

**Issue by Starlynk1** [prusa3d/Prusa-Firmware-MMU#327]
Upated my MK2.5s and MMU2s with the latest Firmware. The MMU fails consistently with the latest firmware. I used the tune function to change it to 10 as seen in forums, however that does not fix the issue. It still continues to overshoot and make a 'grinding' noise when the selector rotates. 

I downgraded to thte 3.13 and have the tune set to 10. It is working as it should and does not do the overshoot grind when homing. Something changed in regards to the home process between these two firmware versions. Considering I have no issues with the downgraded version, it would make sense that whatever the change was may not be needed?

Anyways, hopefully any future updates can fix the homing issue.

**Comment by jmd73** [comment]
@Starlynk1 If the problem is with the MK2.5S firmware, you should probably post this in [Prusa-Firmware/issues](https://github.com/prusa3d/Prusa-Firmware/issues), since this repo is for the MMU firmware.

**Comment by Starlynk1** [comment]
This isn’t for the printers firmware, this is specific to the MMU2S firmware using the most recent version.

Sent from my iPhone

On Jul 30, 2024, at 00:14, jmd73 ***@***.***> wrote:

﻿

@Starlynk1<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Starlynk1&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=XodWtLBkFpvdbc-aEppP_ibPteZq0Cpnye3A6MMh-wk&m=yDIOGTZZJyW3j1RsEj5aXjuYh5nJN1eoUZT_-LzbKUZkfE0iu6ESFTYG6RAwQVBK&s=V1U2OyMBL-ZAT0iWCRCcA-eV2RHA3Sq6HW21ULrUk3k&e=> If the problem is with the MK2.5S firmware, you should probably post this in Prusa-Firmware/issues<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_prusa3d_Prusa-2DFirmware_issues&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=XodWtLBkFpvdbc-aEppP_ibPteZq0Cpnye3A6MMh-wk&m=yDIOGTZZJyW3j1RsEj5aXjuYh5nJN1eoUZT_-LzbKUZkfE0iu6ESFTYG6RAwQVBK&s=bvulfD7T0T3lXGoE7G0V49k2rLDXZUHtebIDoOVz39c&e=>, since this repo is for the MMU firmware.
