### ISSUE TITLE
[QUESTION] MMU2S BOOTLOADER

### ISSUE THREAD

**Issue by shz-fpv** [prusa3d/Prusa-Firmware-MMU#329]
### Question

Encountered address is out of range when burning MMU2S BOOTLOADER using atmelflip,The compilation system I used is debian12.1.0, and I directly compiled the entire project using the make command

**Comment by 3d-gussner** [comment]
I am closing this issue here and transfer it to Prusa-Firmware-MMU

**Comment by 3d-gussner** [comment]
@shz-fpv When you follow the instructions you should create with make `MMU2S_MMU3_FW3.0.3+898.hex` 
Please try using VScode and execute `util/bootstrap.py` to download everything needed.

**Comment by shz-fpv** [comment]
I noticed in the help document that there are relevant drivers under \ Program Files \ Prusa3D \ Rumbo. I used this driver and it prompted me that the installation was successful, but in PruaSlicer2.8.0, it still reported that the device could not be found,
![04f44833-a7ca-4711-a28a-0e9275f21074](https://github.com/user-attachments/assets/ed8caa7a-ec47-4b19-a62b-703fa6985206)

**Comment by shz-fpv** [comment]
Okay, everything seems normal now. I connected to my MMU using USB ASP and burned MMU2S, MMU3, BOOTLOADER3.0.3, hex using progsp. He can now connect to the printer and computer normally. Thank you very much for your reply

**Comment by 3d-gussner** [comment]
@shz-fpv Glad to hear that you found a solution. Please consider to close this issue as it is solved.
